[package]
name = "lambda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-set = "0.5.3"
bitreader = "0.3.6"
bitter = "0.6.1"
byteorder = "1.4.3"
glium = "*"
glm = "0.2.3"
